
name: send_ramdom_item

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Execute Rake task
      run: 
        bundle exec rake send_random_item
      env:
        IDOBATA_ENDPOINT_URL: ${{ secrets.IDOBATA_ENDPOINT_URL }}
        POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
        POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
