name: send_pocket_item

on:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Execute Rake task
        run: bundle exec rake send_random_item
        env:
          IDOBATA_ENDPOINT_URL: ${{ secrets.IDOBATA_ENDPOINT_URL }}
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
